### ISSUE TITLE
Cannot run the example when compiling

### ISSUE THREAD

**Issue by zuuuhkrit** [MrLuit/evm#12]
I'm quite new to node; this failed for me:

    git clone
    npm install
    npm run-script build
    node example/DAI.js

which gives the error (with node version v10.11.0)

    $ node examples/DAI.js
    (node:27306) UnhandledPromiseRejectionWarning: TypeError: findOpcode is not a function
        at EVM.getOpcodes (/home/zuuuhkrit/MrLuit/evm/lib/EVM.node.js:1711:27)
        at EVM.parse (/home/zuuuhkrit/MrLuit/evm/lib/EVM.node.js:1771:28)
        at EVM.decompile (/home/zuuuhkrit/MrLuit/evm/lib/EVM.node.js:1789:34)
        at /home/zuuuhkrit/MrLuit/evm/examples/DAI.js:8:21
        at process._tickCallback (internal/process/next_tick.js:68:7)
    (node:27306) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    (node:27306) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

What am I doing incorrectly?

**Comment by zuuuhkrit** [comment]
This is solved in the 0.3.0 branch.
